name: BetterMechanics
main: net.edoxile.bettermechanics.BetterMechanics
version: 2.0.0-prealpha
author: Edoxile
website: https://github.com/Edoxile/BetterMechanics
commands:
    bettermechanics:
        description: Management command of BetterMechanics
        usage: /<command> reload [cauldron]
        aliases: bm
    pen:
        description: Change the text on signs
        usage: /<command> help
    cauldron:
        description: Manage cauldron and show recipes
        usage: /cauldron help