name: BetterMechanics
main: net.edoxile.bettermechanics.BetterMechanics
version: 2.0.0 build 11
authors: ['Edoxile', 'GuntherDW']
website: https://github.com/Edoxile/BetterMechanics
commands:
    bettermechanics:
        description: Management command of BetterMechanics
        usage: /<command> reload
        aliases: bm
    pen:
        description: Change the text on signs
        usage: /<command> help
    cauldron:
        description: Manage cauldron and show recipes
        usage: /<command> help