name: BetterMechanics
main: net.edoxile.bettermechanics.BetterMechanics
version: 2.0.0-prealpha
author: Edoxile
website: https://github.com/Edoxile/BetterMechanics
commands:
    bettermechanics:
        description: Change the text of signs
        usage: /<command> reload <cauldron>
        aliases: bm