name: BetterMechanics
main: old.bettermechanics.BetterMechanics
version: 1.12-blockbags
authors: [Edoxile, GuntherDW]
website: https://github.com/TweakCraft/BetterMechanics
commands:
    pen:
        description: Change the text of signs
        usage: /pen [clear|set|setline|help]
        aliases: p
    bettermechanics:
        description: Change the text of signs
        usage: /bettermechanics reload <cauldron>
        aliases: bm
