name: BetterMechanics
main: old.bettermechanics.BetterMechanics
version: 1.11
author: Edoxile
website: https://github.com/Edoxile/BetterMechanics
commands:
    pen:
        description: Change the text of signs
        usage: /pen [clear|set|setline|help]
        aliases: p
    bettermechanics:
        description: Change the text of signs
        usage: /bettermechanics reload <cauldron>
        aliases: bm